docs: Update README.md
sern-handler/handler pull request #274
Opened 2023-04-11 18:07 UTC by Murtatrxx

It’s better IG

2023-04-12 03:43 UTC, jacoobes requested changes

2023-04-12 03:43 UTC, jacoobes commented on README.md
> +- Featherweight, lightning-fast. A framework that's tailored to your exact needs.
Havent proven that its lightning fast, cant falsely advertise!

2023-04-12 03:43 UTC, jacoobes commented on README.md
> +- Featherweight, lightning-fast. A framework that's tailored to your exact needs.
Not feather weight either its smaller than sapphire but not super light

2023-04-12 03:43 UTC, jacoobes commented on README.md
> +- Developed reactive. For consistent and reliable backend
Incorrect grammar, revert

2023-04-12 03:43 UTC, jacoobes commented on README.md
> +- Unleash the full potential with a poweful CLI and awesome plugins.
poweful -> powerful

2023-04-13 16:23 UTC, jacoobes commented
I don't really like these changes. The original made sense and the rewording makes it convoluting in my opinion . You add typos and don't bother to check before requesting a review

2023-04-13 16:23 UTC, closed without merging

2023-04-13 19:39 UTC, Murtatrxx commented
Changes makes it pop more

2023-04-13 19:44 UTC, Murtatrxx commented
Why there's two section doing absolutely the same thing?