feat: add all command modules
sern-handler/handler pull request #335
Opened 2023-10-12 10:19 UTC by needhamgary

Also made plugins optional on Executable classes.

2023-10-12 11:59 UTC, needhamgary commented
I attempted to run eslint format, but it was denied due to `//@ts-ignore`'s in the Executable Classes.

2023-10-12 17:33 UTC, jacoobes requested changes

2023-10-12 17:33 UTC, jacoobes commented on src/core/modules.ts
> +import {
import type { 
// all your types
} from 'discord.js'

2023-10-12 17:33 UTC, jacoobes commented on src/core/modules.ts
> + * @since 3.2.0 The wrapper function to create Msg Context2 Menu Commands for sern.
typo! 
Msg Context2 -> Msg Context

2023-10-12 17:33 UTC, jacoobes commented on src/core/modules.ts
> + * @since 3.2.0 The wrapper function to create Msg Context2 Menu Commands for sern.
typo! 
Msg Context2 -> Msg Context

2023-10-12 17:33 UTC, jacoobes commented on src/core/modules.ts
> -import { ClientEvents } from 'discord.js';
merge this import with other import from 'discord'

2023-10-12 17:33 UTC, jacoobes commented on src/core/modules.ts
> -import { ClientEvents } from 'discord.js';
merge this import with other import from 'discord'

2024-07-28 01:46 UTC, closed without merging

2024-07-28 01:46 UTC, jacoobes commented
a little old, and i could figure out the correct typings for dis