Revamp handler
sern-handler/handler pull request #34
Opened 2022-04-17 03:49 UTC by EvolutionX-10

2022-05-07 11:16 UTC, EvolutionX-10 commented
@jacoobes you've started working on it again 👀 
just a suggestion, instead of `feat :` prefer doing `feat:`
a space can affect the way program reads commits

2022-05-17 11:40 UTC, Allyedge approved these changes
We already discussed this, you can merge the branch once the conflicts are solved.

2022-05-18 16:05 UTC, Murtatrxx requested changes
Revert package.json & gitignore, changes, everything else is okay.

2022-05-18 16:05 UTC, Murtatrxx commented on package.json
>    "main": "dist/index.js",
Revert these changes, I did them in my branch

2022-05-18 16:09 UTC, Murtatrxx requested changes

2022-05-20 19:07 UTC, Murtatrxx commented
Keep in mind, resolve conflicts should resolved after revamp-handler is successfully merged with revamp-docs (#47) and  #47 must merged before this.

2022-05-30 02:54 UTC, EvolutionX-10 commented
@jacoobes Closing the PR due to the discussion and solution mentioned in Discord

2022-05-30 02:54 UTC, closed without merging